apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: cicd-sample
description: main application pipeline
serialPipeline:
  stages:
  - targetId: run-qsdev
    profiles: [dev]
  # - targetId: run-qsprod
  #   profiles: [prod]
    ## canary deployment
    # strategy:
    #   canary:
    #     runtimeConfig:
    #       cloudRun:
    #         automaticTrafficControl: true
    #     canaryDeployment:
    #       percentages: [5, 10, 25, 50]
    #       verify: false
    ## multi target
  - targetId: run-qsprod-multi
    profiles: [prod]
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: run-qsdev
description: Cloud Run development service
run:
  location: projects/PROJECT_ID/locations/us-central1
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: run-qsprod
description: Cloud Run production service
run:
  location: projects/PROJECT_ID/locations/us-central1
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: run-qsprod-multi
description: production
multiTarget:
  targetIds: [run-qsprod, run-qsprod-tok]

---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: run-qsprod-tok
description: Cloud Run production service
run:
  location: projects/PROJECT_ID/locations/asia-northeast1