substitutions:
  _REGION: us-central1
steps:
- name: 'gcr.io/cloud-builders/docker'
  dir: 'gig06-03'
  args: ['build', '-t', '${_REGION}-docker.pkg.dev/${PROJECT_ID}/cicd-sample-repo/sample-image:$COMMIT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  dir: 'gig06-03'
  args: ['push', '${_REGION}-docker.pkg.dev/${PROJECT_ID}/cicd-sample-repo/sample-image:$COMMIT_SHA']

# - name: 'google/cloud-sdk:latest'
#   entrypoint: 'sh'
#   dir: 'gig06-03'
#   args:
#   - -xe
#   - -c
#   - |
#     sed -i s/PROJECT_ID/${PROJECT_ID}/g clouddeploy.yaml
#     gcloud deploy apply --file clouddeploy.yaml
#     gcloud deploy releases create rel-${SHORT_SHA} \
#                         --project ${PROJECT_ID}
#                         --region ${_REGION}
#                         --delivery-pipeline my-run-demo-app-1 \
#                         --images=my-app-image=${_REGION}-docker.pkg.dev/${PROJECT_ID}/cicd-sample-repo/sample-image:$COMMIT_SHA
options:
  machineType: E2_HIGHCPU_8
timeout: 3600s